### ISSUE TITLE
VideoNuLA attribute mode is not reset on hard reset

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#104]
Start up an emulated machine with a VideoNuLA. Type:
```
?&FE22=&61:REM turn on attribute mode
MODE 1
```
The BASIC prompt is coloured/corrupted because we're in attribute mode. That's correct.

Choose File->Hard Reset and enter mode 1 again. The prompt is still corrupt, which isn't correct. (I am using current master, commit dac33a4cf0aa3c94d8dfbf7870a01fef74f6de8b.)

I don't think this is likely to be hard to fix, but I wanted to report this before I forgot so I don't have a patch yet. I will look to produce one if no one beats me to it.

Probably worth checking if extended attribute mode suffers the same bug, though it's less likely to be noticed as that only takes effect if ordinary attribute mode is also enabled.

**Comment by SteveFosdick** [comment]
This is fixed in https://github.com/stardot/b-em/commit/aca14309d52fb6aca3fea136b2924829d33ea09d
