### ISSUE TITLE
Installing and/or booting Panos from ADFS/SCSI hard drive seems unnecessarily finicky

### ISSUE THREAD

**Issue by Jim-F** [stardot/b-em#107]
I have never owned a BBC Micro (let alone one with a Tube
co-processor), but I had read about them back in the
80's (I was a fan back then of the NS32016, or NS16032,
or whatever its nom du jour was), and when I discovered
in March of last year that a 32016 Tube emulator had been
created for B-em, I was eager to try it.  I got no
further back then than booting Panos off its installation
floppy, but more recent discussions at
https://github.com/stardot/b-em/issues/91 and
https://stardot.org.uk/forums/viewtopic.php?t=17850
encouraged me to try again.

I downloaded a b-em-master.zip from this repository, current
as of 17 June 2020, and I was able to build B-em (and the
hdfmt utility) under both Windows 10 v. 2004 using Msys2/MinGW64
(and using the recommended Allegro 5.2.2.0 x64 Windows binaries),
and under openSUSE Tumbleweed Linux (using Allegro 5.2.6.0-1.2
from the Tumbleweed repository).  The Windows build required
a bit of fiddling with the supplied Makefile.mingw in order
to get an executable; the Linux build worked out of the box
(after half a dozen trips back to Yast to get all of the required
a la carte Allegro packages).  Both versions of B-em seem to run fine,
and both seem to exhibit the same behavior.  (The Linux is running
on VMWare Workstation Pro v14.1.8 on the Windows 10 machine,
and displays the B-em screen via an X server [Xming]
running on Windows.)

I quickly discovered that if I attempted to install Panos 1.4
from floppy to a freshly-created (via hdfmt) 20 MB SCSI
hard disk image as described below, the installation would
fail with messages:

.
.
.
$ create DD:Library, DD:PanosLib, DD:PanosTests -Dir -NoAbandon
Error in create : can't create a device : 'DD:Library'
Error in create : can't create a device : 'DD:PanosLib'
Error in create : can't create a device : 'DD:PanosTests'
$
$ fcopy D2:*-rif,D2:*-cmd DD:PanosLib
Error in fcopy : destination object is not an output device :
   'DD:PanosLib.Asm32-rif'
[[[ End of command file 'DD:install-cmd' ]]]
->

I finally got this to work, and reproducibly, but the procedures
described below for installing Panos onto a hard disk and then booting Panos
from that hard disk are the result of a great deal of trial-and-error
experimentation.  It is possible that some of this
difficulty is a result of ignorance of proper procedures on my
part, but it also seems likely to me that it is the result
of bugs in B-em.  In particular, the section delimited by "====" below
in the installation procedure, and the sequence that has to be
performed to get Panos to boot from the hard disk, both have a
ritualistic flavor in that they seem to be functioning as
workarounds for some kind of bug in the emulator.

Here is the method I finally got to work reliably:

-----------------------------
Copy "virgin" SCSI disk images, straight from hdfmt.exe
[".\hdfmt.exe scsi0 20M", etc.],
into C:\Users\<Me>\AppData\Roaming\b-em.exe\scsi
(scsi0.dat, scsi0,dsc, . . . , scsi3.dat, scsi3.dsc)

Copy "virgin" b-em.cfg and cmos*.bin files from
directory of extracted b-em-master Github repository
to C:\Users\<Me>\AppData\Roaming\b-em.exe

Start B-em with no command-line options: .\b-em.exe

In B-em menus:

Disc->Load disc 0/2..., select floppy image Pan141.dsd
(Leave checkmarks on "Write Protect disc:0/2"
and "Default write protect".)

Select Disc->SCSI hard disc (checkmark appears)

Select Model->BBC Master 128 w/MOS 3.52 (checkmark appears)
[Any of the BBC Master 128 models will work for Panos
installation, following these steps.  Allegedly the
32016 Tube works with other models; I haven't tried them.]
This resets the emulator.
(Leave the default ROM setup for the model unchanged.)

Select Tube->32016 (checkmark appears)
This resets the emulator again.

====
File->Exit to exit B-em.
(This is important.  The earlier resets, or "File->Hard Reset"
in addition to them, are insufficient to guarantee success.)

Restart B-em as above.
(The settings chosen above will remain:
Pan141.dsd remains loaded as "disc:0/2" and is write protected,
SCSI hard disc is selected,
Model is BBC Master 128 w/MOS 3.52,
and Tube 32016 is selected.)

The screen now says:

Pandora 32000 V2.00         1024 KB
Acorn 1770 DFS
BASIC
*

At the '*' prompt, type
*FADFS
*DISC

(Note again: Unless B-em is exited and restarted as directed above,
these two commands, to switch to ADFS and then back again
to DFS, will not guarantee the success of the Panos installation.)
====

Now, at the Pandora '*' prompt, type
*PANOS
to begin loading Panos 1.4 from installation floppy #1.

Initiate the installation to hard disk by typing at
the Panos '->' prompt:
-> install adfs
The installation will now continue past the point at
which it failed above.  When asked, insert floppy #2,
repeat "install adfs", and the installation will
proceed to successful completion.

[The rest of the installation floppies, #3-#7,
containing the bundled languages and the "Welcome" demo,
can now be installed to the hard disk according to the
instructions in the "Cambridge Co-Processor" manual.
This generally involves inserting a distribution floppy
into drive 0/2 and then (from Panos booted off the
hard drive) typing:
-> dfs:install adfs
]
-----------------------------

Booting into Panos on the hard disk.

To do this you need to switch to ADFS and load Panos
from the hard disk.

But, if you're starting B-em with the configuration saved as
the result of the Panos installation above,
then simply typing: *ADFS
gives the error message "Disc error 50 at  :4/000002".

The sequence *FADFS-*MOUNT-*PANOS
gives the error message "Bad command".

The sequence *FADFS-*ADFS-*PANOS
gives the error message "No directory".

However, the following method seems to work reliably:

-----------------------------
With "Model" set to "BBC Master 128 w/MOS 3.52",
as it was left above, type the sequence:
*FADFS
*MOUNT
*CAT
(Do not skip the *CAT.  You should see the Panos installation
on the hard drive.)
Then, back off one menu item in Model; i.e., change
to "BBC Master 128 w/MOS 3.5".  The emulator will reset.
Now you can type
*ADFS
*PANOS
with no error, and Panos will now boot from the
hard drive.

NOTE:  **Whatever** model of BBC Master 128 the emulator
was set to while installing Panos, in order to boot Panos
from the SCSI hard disk, type the sequence *FADFS-*MOUNT-*CAT
while in that model, and then, as above, change the model
to "BBC Master 128 w/MOS 3.5".  The emulator will reset.
Now you can type *ADFS-*PANOS with no error, and Panos will
boot from the hard drive.  If you performed the installation
with "BBC Master 128 w/MOS 3.5" selected, then change to
a different model of BBC Master 128 to type the sequence
*FADFS-*MOUNT-*CAT, and then change back to
"BBC Master 128 w/MOS 3.5" to type *ADFS-*PANOS to boot
Panos from the hard disk without error.

The final model for subsequently booting Panos from the
SCSI hard disk without error (via *ADFS-*PANOS) seems to
**have** to be "BBC Master 128 w/MOS 3.5".

Following this, after exiting and restarting
B-em, you can just type *ADFS-*PANOS
with no error, and Panos will boot from the
hard drive, **provided** the Model remains
"BBC Master 128 w/MOS 3.5".
If you change it back to "BBC Master 128 w/MOS 3.52"
(or to any other BBC Master 128) then typing
*ADFS once again gives the error message
"Disc error 50 at  :4/000002"
and you have to go through the above *FADFS-*MOUNT-*CAT
sequence, followed by changing the Model back to
"BBC Master 128 w/MOS 3.5", in order to be able to do
*ADFS-*PANOS once again without error.
-----------------------------

I'm not aware of any recommended shutdown sequence for
Panos, but for now before turning off the emulator I'm typing
-> star bye
The "star" Panos command passes what follows through to the
Pandora monitor, and I gather that *BYE flushes everything
to disk, something like "sync" did in older versions of
Unix.  [Edit:  I see from the "Cambridge Co-Processor" manual
that the recommended procedure is to type "-> .quit" to
leave Panos and return to Pandora.  And then, presumably,
*BYE before exiting the emulator.]

**Comment by fordp2002** [comment]
I used Panos on my BBC Micro back in the 1980s. I did not have a harddrive and found Panos far too clunky with just floppies. I am pretty sure I only used ADFS for Panos so if I was trying Panos on BEm I would unplug DFS. In the end I only really used BAS32 and BAS32f.

Having revisited the 32016 and learning it inside  out I can see why they designed the ARM chip. The 320XX was distinctly CISC.

**Comment by Jim-F** [comment]
> [I]f I was trying Panos on BEm I would unplug DFS. . .

Well, Panos comes on seven DFS floppies.  When it's being installed
to an ADFS hard drive, it expects to have simultaneous access
to both filesystems.  During the installation of core components
(from floppies 1 and 2), it's booted from a DFS floppy but needs to simultaneously
access the ADFS hard drive.  Later, during the installation of optional
components (the languages, the Welcome demo, on floppies 3 to 7),
it's booted from the ADFS hard drive, but needs access to the DFS
floppy it's installing the additional component from.

So unplugging the DFS rom probably isn't a good idea.

**Comment by fordp2002** [comment]
I wonder if my floppies were ADFS. In any case I remember needing ADFS to use Panos even without a harddrive. It is the 1980s when I tried Panos proper.

**Comment by Jim-F** [comment]
> Having revisited the 32016 and learning it inside out
> I can see why they designed the ARM chip. The 320XX was
> distinctly CISC.

Well, the appeal of the 32016 (ne 16032) when it (or at
any rate its preliminary description) first appeared was
that it seemed to be the "spiritual" successor to the
PDP-11.  What the VAX "might have been" without the latter's
wildly baroque instruction set.  Though without having
any more programmer-visible registers than a PDP-11, some
folks might have considered the 32016 somewhat "register starved"
notwithstanding its "architectural elegance".

On p. 98 of the second edition of _Computer Lib_ (1987),
Ted Nelson wrote (in a discussion of the newer generation
of microprocessor chips -- the 8086, 286, 386; the 68000, etc.)

------------------
THE SEPULCHRE: THE BEST, but not the most successful:
NATIONAL's 16000.

The National 16000 chip is everything the Motorola 68000
should be, but it came about a year too late.  It will probably
never catch up with the momentum of the Motorola.  A friend
of mine calls it "a study of architectural elegance," much
as the PDP-11 was in 1970.  And so it will have a market niche
determined by those designers who prefer to go with the best
rather than the standard.
------------------

In the event, the 16000/32000 was late, buggy, and slow.

Steve Furber, in an interview on YouTube:

https://www.youtube.com/watch?v=1jOJl8gRPyQ
------------------
ARM Processor - Sowing the Seeds of Success - Computerphile
Apr 24, 2015
Computerphile
------------------

...remarks (at 1:10/13:19):  "We had formed the firm view that
the primary determinant of a computer's performance is the
memory bandwidth you can access to the processor.  Notionally,
the 32016 has a nice instruction set and the 6502 has a primitive
one, but if you looked at the performance you got, it just
scaled with the bandwidth.  The 16-bit microprocessors could not
use the bandwidth that was available in the memory that people
put in these machines.  So you'd spent your money, you'd bought
some bandwidth, and then you were coupling this to a processor
that couldn't use that basic resource.  And this just struck us
as wrong. . ."

Of course, that was then.  These days, CPUs are so blindingly
fast that they need multi-level cache memories in order to run
at full speed.  And if Intel and AMD can implement a "CISC"
architecture like x86-64 in these fast processors (perhaps while
using RISC techniques "under the hood"), then I guess there's
no inherent reason why an equally fast 320XX couldn't have been
made, in time.  But history didn't follow that path.

And these days, the ARM's primary appeal is its low power
consumption, which was not, as Furber remarks, even something
Acorn was thinking about when they first set about designing
a RISC microprocessor.

But the 32000 still has its admirers.  Today, the biggest fan
of the 32000 series is probably a guy named Udo Moeller,
who created "The Web Site to Remember National Semiconductor's
Series 32000 Family"
http://www.cpu-ns32k.net/

;->

**Comment by SteveFosdick** [comment]
Before getting into a discussion on the merits of the 32016...

MOS 3.22 and MOS 3.52 were not released by Acorn - they have been patched since to fix bugs.  I will see if I can work out what has been patched.

I have just now done some experimenting with a SCSI hard disc image on which I had already installed Panos some time ago.  Starting with MOS 3.20 (model labelled as "Master 128") I could get into ADFS without attempting to mount the floppy (which is what causes the error at that point) by holding down F and hitting break.  With the 32016 enabled I then get:
```
Pandora 32000 V2.00 1024KB
Acorn ADFS
BASIC
*
```
If I then `type:
```
mount
panos
```
to mount the hard disc and boot I get 'Bad command' after typing 'panos'.  Examining the contents of the root directory there is no file called Panos there.  Instead it relies on loading it from the Library directory.  So If I issue the commands:
```
*LIB Library
*PANOS
```
it happily boots into Panos.  On my disc image the same is true for MOS 3.22, MOS 3.50 and MOS 3.52.

While removing DFS may not be such a good idea it is possible to change some of the configuration defaults on the Master to make it easier:
```
*co. file 14
*co. hard
*co. dir
```
These change the CMOS settings to make ADFS the default filing system, make it use the hard disc by default rather than the floppy and automatically mount it and set the default directory.  Then after Ctrl-Break you will find the library is set to 'Library' and it is possible to start Panos with just '*panos'.

**Comment by Jim-F** [comment]
> Starting with MOS 3.20 (model labelled as "Master 128")
> I could get into ADFS without attempting to mount the floppy
> (which is what causes the error at that point) by holding
> down F and hitting break. . .
>
> If I issue the commands
>
> *LIB Library
> *PANOS
>
> it happily boots into Panos. On my disc image the same is true
> for MOS 3.22, MOS 3.50 and MOS 3.52. . . .
>
> [I]t is possible to change some of the configuration defaults
> on the Master to make it easier:
>
> *co. file 14
> *co. hard
> *co. dir
>
> These change the CMOS settings to make ADFS the default
> filing system, make it use the hard disc by default rather than
> the floppy and automatically mount it and set the default directory.
> Then after Ctrl-Break you will find the library is set to
> 'Library' and it is possible to start Panos with just '*panos'.

Yes, all this works with my Panos hard disk too, with all Master 128
models.  I guess it was sheerest luck that I was able to find
a sort of ritual dance that allowed me to boot Panos from the
hard disk in the first place, without knowing about "*LIB Library".
There's no hint of this on p.22 of the "Panos Guide to Operations"
manual.

I can guess what "*co. hard" might do, but "*.co file 14"
and "*.co dir" are a bit more obscure -- I'll have to see if
I can find those in a manual.

Edit: Yes, in the "Advanced Reference Manual for the BBC Master" from
http://www.8bs.com/othrdnld/manuals/essentialsmaster.shtml
(sans page numbers, alas), Appendix Two, "Configure CMOS RAM commands"

FILE <ROM> Start-up filing system ROM number
[but counting from 1 instead of from 0 as in the B-em menu?]

FLOPPY/HARD -- Floppy Or Winchester start-up (with HARD,
floppy is selected if no Winchester fitted)

DIR/NODIR -- ADFS or FADFS as default (FADFS does not
mount disc automatically)

[Not clear why the above obviate the necessity for
"*LIB Library".]

Anyway, thanks!

**Comment by SteveFosdick** [comment]
> FILE Start-up filing system ROM number
> [but counting from 1 instead of from 0 as in the B-em menu?]

The ROM numbers are the same ones used by the *ROMS command, though *CONFIG expects the ROM number in decimal rather than hex.

> [Not clear why the above obviate the necessity for
> "*LIB Library".]

I'll see what I can discover.

After all that I am still wondering if there is a bug here.  With the right CMOS config things are much easier but there shouldn't be any cases where re-starting b-em works and doing a hard reset does not.  I'll see what exactly the hard reset does and if anything is obviously missing.

**Comment by SteveFosdick** [comment]
I have raised bug #108 to document the MOS ROM patches.

**Comment by SteveFosdick** [comment]
I think the conclusion of this is that this is more due to Master 128 CMOS defaults than due to B-Em.

**Comment by egrath** [comment]
> 
> [Not clear why the above obviate the necessity for "*LIB Library".]
> 
Sorry for digging out such a old and already closed ticket, but i think the information might be useful for people getting here through google searches. Your question is answered in the "Acorn Winchester Disc Filing System User Guide" on Page 16/17.

In summary: If ADFS is started with automatic mounting (*CONFIGURE DIR or with *ADFS), then the first directory in $ with a name starting with LIB is chosen as the library (=where MOS looks for unknown commands). If no such directory exists, the root directory is chosen. As on the Harddisc where Panos is installed a directory $.Library exists, this is chosen as the library. If however, ADFS is entered without automatic mounting (*CONFIGURE NODIR or with *FADFS), then the library is not set up and has to be done manually with *LIB.
