### ISSUE TITLE
BBC B, 65C02, Acorn 1770

### ISSUE THREAD

**Issue by fordp2002** [stardot/b-em#110]
I pull b-em this week and build it on my Ubuntu 20.04 AMD64 Machine the above build shows "mem: unable to load ROM slot 15 with basic4, ROM file not found" when booting.

**Comment by SteveFosdick** [comment]
Oops, it was missing from the roms directory.  Try now.

**Comment by fordp2002** [comment]
I just tested it. You put it in the wrong directory!

**Comment by SteveFosdick** [comment]
Ok, I have pushed another commit to move it.

**Comment by fordp2002** [comment]
Thanks for fixing it so quick.
