### ISSUE TITLE
Unable to compile with Linux

### ISSUE THREAD

**Issue by bodhi-baum** [stardot/b-em#111]
I wanted to try to compile the latest master with Linux and therefore I installed Allegro 5.2 from https://launchpad.net/~allegro/+archive/ubuntu/5.2 as recomended in the docs. Unfortunately I didn´t succeed compiling it. Even after a couple of tries it always stated that there is no Allegro 5.2 installed. What did I do wrong?

**Comment by fordp2002** [comment]
Which distro?

**Comment by SteveFosdick** [comment]
Looks like Ubuntu.  With Debian-based distro, including Ubuntu, most packages are split into a run-time version and a dev version.  To compile B-Em you need the -dev version of Allegro 5.

**Comment by fordp2002** [comment]
I can add instructions for Ubuntu 20.04 later. It is easy to compile and just needs dependencies using apt-get.

**Comment by fordp2002** [comment]
Try this:<br>
https://github.com/stardot/b-em/wiki/Building-on-Ubuntu-20.04<br>
 and let me know if it works. It ill probably work on other Debian based versions/distros.

**Comment by bodhi-baum** [comment]
Well, I just updated to Linux Mint 20 - which is an Ubuntu derivate - and therefore I neither can add the Allegro-repository nor is the right version available in the Mint-repositories. Seems that I have to wait until someone updated either one or the other. I will try later and give a feedback then.

**Comment by bodhi-baum** [comment]
Now I had installed all necessary packages and the compilation went well almost to the end. Only at the very end there was the following error message and the process was aborted.

In file included from config.c:7:
ddnoise.h:4:10: fatal error: allegro5/allegro_audio.h: Datei oder Verzeichnis nicht gefunden
    4 | #include <allegro5/allegro_audio.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:1228: b_em-config.o] Fehler 1
make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …
make[1]: Verzeichnis „/home/bodhi/b-em/src“ wird verlassen
make: *** [Makefile:426: all-recursive] Fehler 1

**Comment by SteveFosdick** [comment]
Does Mint (possible from practice at either Debian or Ubuntu) package the various pieces of Allegro separately?  Allegro consists of a core and a number of add-ons with audio being one of the add-ons.

**Comment by bodhi-baum** [comment]
Hello Steve, you are right, Mint packages the various pieces separatly. Now, after I installed all available Allegro5-packages, compiling went well.
