### ISSUE TITLE
Add ROMSEL info to debugger to show current RAM state.

### ISSUE THREAD

**Issue by kieranhj** [stardot/b-em#113]
I somehow thought this had been removed from the debugger but turns out it was only in my (very ancient) local build. It's very useful though! I'm far too far behind master to submit a PR but just add the following lines to debugger.c under the 'r' command:

```
	if (!strncasecmp(&ins[d], "ram", 3))
	{
		sprintf(outs, "    System RAM registers :\n");
		debug_out(outs);
		sprintf(outs, "    ROMSEL=%02X ram4k=%02X ram8k=%02X ram12k=%02X ram20k=%02X vidbank=%04X\n", romsel>>14, ram4k, ram8k, ram12k, ram20k, vidbank);
		debug_out(outs);
	}

```

**Comment by SteveFosdick** [comment]
That looks like a useful feature.  I  will make the equivalent change to the current debugger.  BTW Dominic has contributed symbols to the debugger.

**Comment by SteveFosdick** [comment]
Ok I have made the change and it is in the latest master.
