### ISSUE TITLE
Glitch in 8271 emulation?

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#125]
Hi,

The title of this issue is a bit speculative. If I set b-em (I'm using commit b4e3a717af3f37b331dc50eaac2509ba309b31ef for this; let me know if you'd like me to try another version) to emulate a BBC B with 8271 and install Acorn DFS 1.2, running the program on the attached bootable zipped .ssd hangs after a while. If I break into the debugger it seems to be stuck in this loop inside DFS:
```
D:ACB1: 30FB       BMI ACAE    >s
D:ACAE: 2C80 FE    BIT FE80    >s
D:ACB1: 30FB       BMI ACAE    >s
D:ACAE: 2C80 FE    BIT FE80    >s
```
The program just reads random 512-byte blocks from the disc using OSWORD &7F, using code taken from beebwiki to do the actual read. It doesn't seem to hang on BeebEm 4.15 emulating a BBC B with DFS 1.2, or on b-em if I emulate a BBC B with Acorn 1770 DFS 2.26.

I think the random time delay in the test program is important, my initial version just kept calling OSWORD &7F as fast as possible and it didn't seem to lock up even though I left it running for a while.

I think Acorn DFS 0.9 does the the same, but I haven't double checked this with this exact test program.

Let me know if you need any more information, of course, or if you'd like me to try anything.

Cheers.

Steve

[z.zip](https://github.com/stardot/b-em/files/5319563/z.zip)

**Comment by SteveFosdick** [comment]
I can reproduce it.  I'll investigate.

**Comment by SteveFosdick** [comment]
There were two separate bugs.  Try https://github.com/stardot/b-em/tree/sf/discimd - a5318bc6f4e2d3d30ea8a1b99785c6f3ebb13fb5 should fix.

**Comment by ZornsLemma** [comment]
Thanks, that seems to have fixed it - both the program I attached earlier to reproduce the bug, and the actual case I originally noticed the problem (running the benchmark for my Acorn port of Ozmoo: https://stardot.org.uk/forums/viewtopic.php?f=2&t=19975&start=240#p288827). Thanks again, I don't think I could have fixed this one myself.
