### ISSUE TITLE
Unable to open HFE image from within b-em

### ISSUE THREAD

**Issue by PeterBBCUser** [stardot/b-em#127]
I can open a hef from explorer associated with b-em, but if I try to load a hfe disc from within b-em under disk load disc 0/2 it is not shown as a known disc format (see attached pic). this is with the latest release v640fd90
![b-em-hfe](https://user-images.githubusercontent.com/33581895/95673684-2e5b9880-0bab-11eb-8206-7c414ad346bf.png)

**Comment by SteveFosdick** [comment]
I have pushed a commit to master that should solve this.  I will re-build the release package.

**Comment by SteveFosdick** [comment]
This release: https://github.com/stardot/b-em/releases now has the fix. See https://github.com/stardot/b-em/commit/1334997f0dbb9b76b805d1336f3fa0b1e12759fe for the change itself.
