### ISSUE TITLE
Turbo second processor behaviour can be enabled even when using non-turbo second processor

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#128]
Hi,

I'm not sure if this is the latest version of the turbo second processor code, but on the current master branch, 6502tube.c's do_writemem() has this:
```
   if (addr == 0xfef0 && tuberamsize > 0x1000) {
        if (value & 0x80)
            enable_turbo();
        else
            disable_turbo();
    }
```
Note that there are only three zeros on the value tuberamsize is being compared against. 
I think this is wrong and means by poking &FEF0 you can enable the turbo behaviour even on a normal second processor; it should be 0x10000 (four zeros) or TUBE_6502_RAM_SIZE.

Cheers.

Steve

**Comment by ZornsLemma** [comment]
On a slightly different note: the b-em implementation seems to use &371 to control banking for "(&70),Y" operands, but PiTubeDirect (https://github.com/hoglet67/PiTubeDirect/blob/master/src/lib6502.c) seems to use &370 to control this. In other words, b-em seems to use a base of &301 for the banking control page, while PiTubeDirect seems to use &300. Am I misreading the code here? I don't know which is right anyway; does code have to write to both &370 and &371 on real hardware so both implementations are correct?

**Comment by SteveFosdick** [comment]
On the first point I believe you're right.  When started as the Turbo 2nd processor it allocate more RAM and the idea was to avoid being able to turn on turbo mode if the RAM array is too small but the value in the comparison is wrong.  I'll patch that.

**Comment by SteveFosdick** [comment]
On the second point I believe they are both doing the same thing.  Here is the PiTubeDirect implementation of just zero page indirect for comparison:
```
#ifdef TURBO

#define indzp(ticks)                \
  tick(ticks);						\
  {							\
    byte tmp;						\
    tmp= MEM(PC++);					\
    ea = MEM(tmp) + (MEM((tmp + 1)&0xFF) << 8);		\
    if (turbo) {						\
      ea += ((MEM(((tmp + 1)&0xFF)+0x300)&0x03) << 16);		\
    }								\
  }

#else 
```
So in the equivalent of your example (no Y) of (&70), tmp will get set to &70, so tmp + 1 will be &71 - that then gets added to 0x300.  Adding &71 to &300 is equivalent to adding &70 to &301.

There may be a little bug in that if you issue an instruction with (&FF) I think the PiTubeDirect implementation will pick up the MSB from 0x300 and the B-Em version from 0x400.

**Comment by ZornsLemma** [comment]
Thanks. I had missed the +1 in the PiTubeDirect code, so I think you're right and they are equivalent. As for the possible little bug, as &FF is part of the OS workspace in practice it's not likely to cause a problem, and I guess we won't know what the actual hardware does unless someone gets hold of one.

**Comment by SteveFosdick** [comment]
The patch is in master, let's close this unless/until we find the proper behaviour for the wrap.
