### ISSUE TITLE
Partly broken build on macOS

### ISSUE THREAD

**Issue by lurkio** [stardot/b-em#140]
Some strange workarounds are needed if you want to build B-em on macOS Mojave or Catalina:

https://stardot.org.uk/forums/viewtopic.php?p=312835#p312835

The *gtest* and *sdf2imd* directories are empty. What are we missing out on?!

**Comment by SteveFosdick** [comment]
See: https://stardot.org.uk/forums/viewtopic.php?p=312952#p312952
Conditional compilation for unlocked I/O in https://github.com/stardot/b-em/tree/sf/issue140, commit https://github.com/stardot/b-em/commit/84d3a464f30153ed7b1f0d3664d24d2e1e9c338c

**Comment by SteveFosdick** [comment]
Thanks, Steve, all changes merged.
