### ISSUE TITLE
Integra models give Language? error

### ISSUE THREAD

**Issue by hoglet67** [stardot/b-em#146]
I'm trying to do some testing of MMFS with Integra in B-Em.

I can't get the past the Language? error when I switch to the B-Em model

(I'm using d3ac42ea)
[
![Screenshot from 2021-03-21 18-45-12](https://user-images.githubusercontent.com/1951463/111917069-e607a700-8a75-11eb-8251-18c880cc6f4f.png)
](url)

I've tried a clean build, and also deleting the old  $HOME/.config/b-em folder

Is this expected?

Help!

**Comment by ZornsLemma** [comment]
I think holding down @ while powering on may help by resetting the CMOS.

**Comment by hoglet67** [comment]
Thanks, that was it....
