### ISSUE TITLE
ROM configuration/menu breaks a little when enabling tube

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#147]
This is with commit d3ac42ea967ac78853cbb60d06a096c58a77a470 (current master).

I haven't investigated too deeply, but here's one series of steps to show a problem. I have a disc in drive 1 with the MAMMFS ROM image on it; I'm not using MAMMFS, this is just a way to test sideways RAM.

- Select Master 128 mode with no co pro.
- Close b-em and re-start it, it starts up in Master 128 mode with no co pro.
- Use the ROM menu to make bank 3 RAM.
- *SRLOAD :1.MAMMFS 8000 3 Q
- CTRL-BREAK
- *ROMS shows MAMMFS in bank 3
- Choose Tube->6502 External - the emulated machine is reset and starts up with a copro
- *ROMS doesn't show MAMMFS - this is fair enough, the emulated machine has been powered down to connect the copro
- The ROM menu shows bank 3 is still sideways RAM (I could see arguments for changing this back to the ROM or keeping it as RAM, but I'm quite happy with it still showing as RAM)
- *SRLOAD :1.MAMMFS 8000 3 Q
- CTRL-BREAK
- *ROMS *doesn't* show MAMMFS - it doesn't look like bank 3 actually *is* sideways RAM
- un-tick the "RAM" option on the bank 3 submenu
- *SRLOAD :1.MAMMFS 8000 3 Q
- CTRL-BREAK
- *ROMS *does* show MAMMFS - bank 3 is showing as RAM in the main ROM menu, but the RAM option on the submenu isn't ticked

I hope that makes sense. I think the underlying issue is that when adding a copro, the newly added sideways RAM bank is lost but the ROM menu isn't updated and after that things are always a bit of sync and confusing. I could accept keeping or losing the newly added sideways RAM bank when adding the copro, but the ROM menu should stay consistent.

**Comment by SteveFosdick** [comment]
Yes, when adding or removing a co-pro the machine is hard reset, i.e. the model, as defined in the config file, is re-loaded.  That means the assignment of RAM vs. ROM is as per the model config.

For some machines that is hard-coded - the Master and B+, for example, have sideways RAM exactly where it would be on a real machine.  Most other models have sideways RAM wherever there isn't a ROM loaded.

So that's another place the ROM menu needs to be refreshed.

**Comment by SteveFosdick** [comment]
Try https://github.com/stardot/b-em/tree/sf/issue147

**Comment by ZornsLemma** [comment]
Sorry it took me so long to get back to you on this. I've just tried that branch and I can't reproduce this, thanks very much for the quick fix!

**Comment by SteveFosdick** [comment]
This is now merged.
