### ISSUE TITLE
Reads from FE3C will access system VIA on non-Integra machines

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#154]
I don't think this is likely to cause big problems, but I'm not sure it's right. 6502.c has:
```
        case 0xFE3C:
            if (integra)
                return cmos_read_data_integra();

        case 0xFE40:
        case 0xFE44:
        case 0xFE48:
        case 0xFE4C:
        case 0xFE50:
        case 0xFE54:
        case 0xFE58:
        case 0xFE5C:
                return sysvia_read((uint16_t)addr);
```

There's no "break;" after the "if (integra)" so the code will fall through to the system VIA case.

**Comment by SteveFosdick** [comment]
I think you're right.  I have added the break in https://github.com/stardot/b-em/commit/e5adcafef6ac60137fd1d98bcc44974440a2e238

**Comment by ZornsLemma** [comment]
Great, thanks!
