### ISSUE TITLE
CMOS gets mixed up between Integra-B and other machines

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#155]
I have a rough idea what's going on but let me try to illustrate the problem first.
- Start b-em in Master 128 mode, *CONFIGURE LANGUAGE 12 (BASIC) and *CONFIGURE FILE 9 (DFS).

- Close and re-start b-em - it opens in Master 128 mode with DFS and BASIC selected, which is correct.

- Change the model to "BBC B w/1770 FDC + Integra-B". Type:
```
*BOOT HELLO
```

- This sets up the Integra-B to automatically type "HELLO" when powered on. You can verify this has worked by doing

```
*BOOT ?
```

- Choose File->Hard Reset. The Integra-B will *not* type HELLO, although it should.

- Change the model back to Master 128 mode - it will try to boot into ADFS, not DFS as we previously *CONFIGUREd.

I think the problem is that main_restart() does
```
    cmos_save(&models[oldmodel]);
```
but not all callers of main_restart() have set oldmodel up correctly. In particular, in the example above, when we hard reset the Integra-B machine, oldmodel still refers to the Master 128 and so we save the Integra-B CMOS as if it were the Master 128 CMOS. I base this conclusion on adding:
```
    fprintf(stderr, "SFTODO: main_restart() oldmodel=%d curmodel=%d\n", oldmodel, curmodel);
```
just above that cmos_save() line in main_restart() and watching the output as I play around with hard resets and model switches.

I am seeing this with e5adcafef6ac60137fd1d98bcc44974440a2e238 (current master) but think this has been happening for a while. (I don't know if Integra-B got added at some point in the last few months or I just noticed it for the first time in the last few months.)

**Comment by SteveFosdick** [comment]
I'll have a look.

**Comment by SteveFosdick** [comment]
Looking at the other places oldmodel is used and where main_restart is used it seems the general assumption in the code is that oldmodel is only different from curmodel when the model is being changed.  This explains why it works for the first model change, i.e. in your test case changing from the Master 128 to the Model B with Integra, but then fails on the 2nd model change.

Here's one way to fix that: https://github.com/stardot/b-em/commit/4b911f7ff101eb88135e272c3bacfc40b400c667

Re-trying with your test case that now works for me.

**Comment by ZornsLemma** [comment]
Thanks, that certainly seems to fix this issue - much appreciated! I will keep using this branch and see if I spot any other problems.

**Comment by SteveFosdick** [comment]
Ok, I have merged this fix into master.
