### ISSUE TITLE
File not found errors using games MMB file

### ISSUE THREAD

**Issue by SteveFosdick** [stardot/b-em#163]
See: https://stardot.org.uk/forums/viewtopic.php?p=343590#p343590

When using the common MMB with a games menu on disc 0, often the games won't load giving a file not found error.

**Comment by SteveFosdick** [comment]
This appears to be an error either index lookups or offset calculation:
![issue163a](https://user-images.githubusercontent.com/1048671/146653128-3350e22a-2a5f-4c7a-bc5d-7396fed89bd4.png)

**Comment by SteveFosdick** [comment]
I have created a branch with a fix for this: https://github.com/stardot/b-em/tree/sf/issue163

See commit https://github.com/stardot/b-em/commit/85d1bec9c57e2306ab30f0ed84210f43646fb855

**Comment by stuaxo** [comment]
@SteveFosdick is it worth making this a PR ?

**Comment by SteveFosdick** [comment]
Thank branch was merged to master back in December.
