### ISSUE TITLE
Warning logging on windows is not visible

### ISSUE THREAD

**Issue by hoglet67** [stardot/b-em#17]
Instead of sending this to stderr, we should probably write this to a file.

(This is what BeebEm does)

**Comment by SteveFosdick** [comment]
Ok, leave that one with me.

**Comment by SteveFosdick** [comment]
Pull request #19 is in to fix this.  Out of the box the new logging setup will write warnings to the b-emlog.txt file.  To have warnings popup as dialog boxes add "logging = 1905" to the b-em.cfg file.  At the moment there is no GUI to configure the logging - we could add this later is there is demand.

**Comment by SteveFosdick** [comment]
Now pull request #21

**Comment by SteveFosdick** [comment]
This is closed by merging the sf/logging branch.
