### ISSUE TITLE
snapdump name collision

### ISSUE THREAD

**Issue by atsampson** [stardot/b-em#176]
The new [snapdump](https://github.com/stardot/b-em/commit/d62eb2a731d403882e969a26ceba99660088bd1f) program has the same name as [snapdump](https://sourceforge.net/p/fuse-emulator/fuse-utils/ci/master/tree/snapdump.c) in fuse-utils (added in 2017).

Would you consider renaming b-em's `snapdump` to `bsnapdump`, or something like that? Otherwise distribution packagers will have to pick a new name for it anyway - it's quite likely that people interested in BBC emulation will also be interested in Spectrum emulation and will want to have both packages installed.

**Comment by SteveFosdick** [comment]
No problem, I'll rename it.

**Comment by SteveFosdick** [comment]
I have pushed a commit with your suggested name.

**Comment by atsampson** [comment]
Brilliant - thanks for the very quick response! I've just rebuilt with your new commit and it works for me.
