### ISSUE TITLE
BUG: Symbols when tracing

### ISSUE THREAD

**Issue by TobyLobster** [stardot/b-em#178]
At the end of the function `dbg6502_disassemble` in `6502debug.c` the `else if` statement on line 430 should use a greater than symbol, not less than. This is the calculation to display a symbol with a negative offset. As it stands the nearby symbols are still shown but *without* the proper negative offset.

**Comment by SteveFosdick** [comment]
Fixed in https://github.com/stardot/b-em/commit/d66ded886e5c8a9e782028654fbdcc900ff7a76a
