### ISSUE TITLE
Compiler error on macOS

### ISSUE THREAD

**Issue by rjpontefract** [stardot/b-em#215]
In the recent commits the following error has been re-introduced when building on macOS with clang.

```
ARMulator/armemu.c:820:21: error: expected expression
                    int do_int = 0;
                    ^
1 error generated.
```

**Comment by SteveFosdick** [comment]
The reversion came from merging the Sprow branch.  Checking that commit, the failing line had been re-introduced.  I have re-deleted it and push the change.  It still compiles fine under gcc - can you check if it works on MacOS?

**Comment by rjpontefract** [comment]
Thanks, it all builds cleanly on macOS.
