### ISSUE TITLE
Core dump on startup with e624e51

### ISSUE THREAD

**Issue by hoglet67** [stardot/b-em#217]
Happy New Year Steve!

I'm running on an oldish Ubuntu 18.04 installation.

With e624e51 I get:
```
b-em: /build/allegro5-cSE4AD/allegro5-5.2.3.0/src/bitmap_draw.c:34: _bitmap_drawer: Assertion `bitmap != dest && bitmap != dest->parent' failed.
Aborted (core dumped)
```

With ff93fb0 (the previous master) it works fine.

It looks like this comes from the merge of  sf/issue214.

Dave

**Comment by SteveFosdick** [comment]
Try this branch: https://github.com/stardot/b-em/tree/sf/issue217

Interestingly, it looks like it is not that the version of Allegro you have is old but that it was built with assertions compiled in.  That assertion is still there in source of the current version.

**Comment by hoglet67** [comment]
That's fixed it, thanks Steve.

**Comment by SteveFosdick** [comment]
Thanks, Dave, now merged to master.
