### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by antonioleal** [stardot/b-em#223]
Hi,
On my box the last commit e897872679d5b8108b04d8381e3606483c687b54 when loading a game from my mmb file produces a segmentation fault, the previous commit 388e1d8db63c4f6b0e68d6e4235b9bd16984a65b didn't have this problem.
Can you reproduce it?

I tried on latest debian and slackware

Cheers,
António

**Comment by SteveFosdick** [comment]
Does this happen on all games or just a specific one?

**Comment by antonioleal** [comment]
Hi
I tried 3 or 4 random  games all with the same result.I maintain a Slackware build script for B-em at Slack builds.org, usually tracking your updates.

Cheers Antonio


Yahoo Mail: Search, Organize, Conquer 
 
  On Wed, Mar 6, 2024 at 15:03, Steve ***@***.***> wrote:   


Does this happen on all games or just a specific one?

**Comment by SteveFosdick** [comment]
Should be fixed in: https://github.com/stardot/b-em/commit/5557a369a0740bbb8cc11f345a05f9e7641c87e2

**Comment by antonioleal** [comment]
Issue fixed
