### ISSUE TITLE
VDFS always *RUNs in the I/O processor

### ISSUE THREAD

**Issue by davidgiven** [stardot/b-em#27]
If you have a Tube system and you try to run a transient executable on the Tube, it gets loaded and run in the I/O processor instead. With sometimes hilarious results.

https://www.youtube.com/watch?v=4icSz0ks2pE

Modifying the code in `run_file()` to load the binary into the Tube is really easy, but actually calling the code isn't, and may need ROM support --- out of my pay grade, unfortunately.

**Comment by SteveFosdick** [comment]
That looks like an oversight.  I can see I modified osfile_load to load files with tube addresses into the tube processor if one is enabled but I have forgotten to do that for run_file.  As you say that does leave the question of how to start the tube processor running in the right place.  The modules to emulate the tube processors are all part of b-em so it should be possible host-side but I don't know if there is anything the tube processor should do before jumping to the newly loaded code.

**Comment by davidgiven** [comment]
I had a look at beebem's version, but it all works quite differently. I think it's loading the data directly, but then returning a status code to the I/O processor ROM to tell it to start running. Does the beebem version use the same ROM as b-em? In which case the functionality might already be there.

**Comment by SteveFosdick** [comment]
The history to this is that, as far as I know, J.G Harston wrote the ROM, based on some work by Sprow,  for use in a completely different emulator, probably not even PC-based.  He published the source code for the ROM and nothing happened for a while.  I had the idea to implement VDFS in B-em after discovering the ROM and set about it.  Once I had finished, or nearly so - I can't quite remember, J.G.Harston decided to implement it for BeebEm too but did it his own way.

I know I have tweaked the ROM a little and maybe he has too so the two versions will now not be the same but they should be a lot more similar than the host-side code is and it should be possible to do something similar to what he has done to start execution in a tube processor.

**Comment by SteveFosdick** [comment]
Looking at the tube documentation JGH had kindly made available on his website it would certainly be possible for the host-side VDFS code to set a flag for the code in the VDFS ROM to initiate tube execution.  That code would need to acquire the tube (call &0406 with A=C0 + FS number) then call the same tube entry point &0406 with A=4 and XY=address in IO memory of 4 bytes containing the address in tube memory at which to start execution.  I will see if I can get round to implementing this soon.

**Comment by SteveFosdick** [comment]
Looking at the tube documentation JGH had kindly made available on his website it would certainly be possible for the host-side VDFS code to set a flag for the code in the VDFS ROM to initiate tube execution.  That code would need to acquire the tube (osbyte

**Comment by SteveFosdick** [comment]
I have committed a change to branch issue28 which I think works correctly.  I haven't written anything that runs in the tube 6502 so I tried saving a copy of the HiBasic ROM with the correct load/exec addresses and *RUNning that.  It seemed to work.  Do you have a better test case?

**Comment by davidgiven** [comment]
It looks like this works fine --- I built most of a program with Cowgol on VDFS (which is what I mainly want to use it for) and it ran all the binaries properly.

It did then fail for other reasons, but this at least I believe is fixed. Thank you very much!

**Comment by SteveFosdick** [comment]
Thanks, David.
