### ISSUE TITLE
Compiler warning on VideoNULA video.c on Windows

### ISSUE THREAD

**Issue by SteveFosdick** [stardot/b-em#31]
When compiling on Windows, gcc gives the following warnings:

gcc.exe -std=gnu99 -O3 -Wall -DBEM -DVERSION=\"Win32\" -DINCLUDE_DEBUGGER -DUSE_MEMORY_POINTER -c video.c
video.c: In function 'videoula_write':
video.c:130:78: warning: array subscript is below array bounds [-Warray-bounds]
video.c:130:78: warning: array subscript is below array bounds [-Warray-bounds]
video.c:130:78: warning: array subscript is below array bounds [-Warray-bounds]
video.c:130:78: warning: array subscript is below array bounds [-Warray-bounds]
video.c:130:78: warning: array subscript is below array bounds [-Warray-bounds]
video.c:130:78: warning: array subscript is below array bounds [-Warray-bounds]
video.c:130:78: warning: array subscript is below array bounds [-Warray-bounds]
video.c:130:78: warning: array subscript is below array bounds [-Warray-bounds]

This is >gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/4.6.2/lto-wrapper.exe
Target: mingw32
Configured with: ../gcc-4.6.2/configure --enable-languages=c,c++,ada,fortran,objc,obj-c++ --disable-sjlj-exceptions --with-dwarf2 --enable-shared --enable-libgomp --disable-win32-registry --enable-libstdcxx-debug --enable-version-specific-runtime-libs --build=mingw32 --prefix=/mingw
Thread model: win32
gcc version 4.6.2 (GCC)

**Comment by ThomasAdam** [comment]
I suspect this is because the array index is `int c`.  I suspect using `unsigned int c` will make the warning go away.

However, since I can't generate this warning on Unix, I'm taking an educating guess.  But do please try it and see what happens.

**Comment by SteveFosdick** [comment]
Thanks, for the reply Thomas.  I logged the bug to make sure I didn't forget but didn't check the code immediately.  Looking at it now I think I can see the problem.  The line the compiler highlights is in the loop:

```
for (c = 0; c < 16; c++)
{
    if ((ula_palbak[c] & 8) && nula_flash[c-8]) ula_pal[c] = nula_collook[ula_palbak[c] & 15];
    else                 ula_pal[c] = nula_collook[(ula_palbak[c] & 15) ^ 7];
}
```

With c varying between 0 and 15 the expression nula_flash[c-8] looks problematic.  Of course, the test in the if statement may mean this is never executed when c < 8 but I don't know enough about how this code works.  Interestingly the compiler has issued eight warnings for the same line which means it must have decided to unroll this loop and hence eight out of the 16 iterations generate the warning.

Kieran, one for you, I think.

**Comment by hoglet67** [comment]
I would change the c-8 to c&7, it will have the same effect, but can't go negative.

**Comment by SteveFosdick** [comment]
That solves the warning.  I have made the change and pushed it to master.
