### ISSUE TITLE
open with .uef/.ssd files

### ISSUE THREAD

**Issue by PeterBBCUser** [stardot/b-em#46]
If you click on a uef file associated with b-em it does not load it in b-em as a tape but try's to load it as a disc image.

**Comment by SteveFosdick** [comment]
I have committed a change to Master that fixes this.  If you need an Windows executable let me know.

**Comment by PeterBBCUser** [comment]
Yes a windows executable would be grate.

**Comment by SteveFosdick** [comment]
The release at https://github.com/stardot/b-em/releases/tag/master-pre1 includes the fix for this issue.
