### ISSUE TITLE
Master Turbo mode leaves 6502 second processor permanently selected

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#47]
I just built 4ce6e9dbe309fe77088393e693cc42f3255a39e3 (current master HEAD) on Linux. It works great generally, but if I choose Settings->Model->Master Turbo, it seems to enter a strange stuck state where I can't turn the second processor off. If I subsequently choose Settings->Model->BBC Master 128 it doesn't turn the second processor off. Choosing a different second processor or none from Settings->Second processor doesn't make any difference - I always have a 6502 second processor.

Cheers.

Steve

**Comment by SteveFosdick** [comment]
Steve, fixed in the latest commit to master: https://github.com/stardot/b-em/commit/c22c68b4f892463bcb97183e10a3128b7a32398c

**Comment by ZornsLemma** [comment]
Works great, thank you! Should I close this issue or will you?

**Comment by SteveFosdick** [comment]
Thanks for the feedback, I'll close it.
