### ISSUE TITLE
Provide a key shortcut to toggle between 100% speed and 500% speed

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#49]
I like to use 500% speed when running the test suite for a program I'm developing, but I have to drop back to 100% when I want to type something in to the emulated machine. It would be nice if there was a single key I could press to toggle between normal speed and maximum speed instead of having to navigate the menu each time.

Alternatively - but I suspect this is hard/impossible - if some magic could make it possible to type normally even when the machine is running at 500% speed, I wouldn't need the toggle and could just leave the machine at 500% all the time.

I hope it's OK to raise a feature request as an issue like this, please let me know if it's not.

Thanks.

Steve

**Comment by kieranhj** [comment]
PAGE UP key is meant to run b-em in unlimited update - is that not still the case?

**Comment by ZornsLemma** [comment]
It looks like you're right Kieran, but that seems to be a transient thing while you are holding down PAGE UP - my test suite can run for minutes/hours at a time (but if it crashes early, as it often does during development :-) it may only be seconds) so I'd like to be able to achieve a similar effect via a toggle.

**Comment by SteveFosdick** [comment]
As I understand it, the PguP key is "free run" mode, i.e. as fast as possible.  If we allocate another key to a speed change but this time to act as a toggle rather than only working while held down would this "free run" be the best thing to do it with?  What key should we use?  Page Down is already taken with "pause".

**Comment by ZornsLemma** [comment]
Free run sounds good to me - I want maximum speed, I only use 500% because that's the fastest you can choose from the menu.

I don't have any strong opinions on what key we should use. Could we use something like shift+Page Up or ctrl+Page Up, the idea being that this is a kind of variation on the usual Page Up functionality?

**Comment by SteveFosdick** [comment]
I have implemented this on the new Allegro5 port in commit https://github.com/stardot/b-em/commit/ce4c35515fccdc1ea2bfd0e6c2c06c01cbc9edbd as it is easier there.  I'll have a look how easy it will be to do in the existing B-Em.

**Comment by SteveFosdick** [comment]
And it is now implemented in master: https://github.com/stardot/b-em/commit/99b99ad31138012f509f0ba95de91fda9ee95723

In both cases hitting the PgUp key always starts free-run mode.  When you release the PgUp key B-Em check the status of the shift keys.  If neither shift key is in force it cancels free-run and returns to normal speed just like before.  If one of the shift keys is down it leaves free-run in force,  Them to cancel free-run you press PgUp (which does nothing as free-run is already in force) then release it without shift and free-run is cancelled.

**Comment by ZornsLemma** [comment]
I just built the latest code from master, works brilliantly for me, thanks a lot. This will save a lot of low-level irritation during development!

**Comment by SteveFosdick** [comment]
Thanks for getting back to me Steve, I'll close this now.
