### ISSUE TITLE
Support 65C102 "turbo" second processor

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#54]
I know it's only a small thing, but I would like to see the appropriate startup banner (and possibly any other subtle behaviour changes) when using a Master Turbo. The relevant ROM is available at mdfs.net (http://mdfs.net/Software/Tube/6502/) and it works fine if I drop it in in place of the existing second processor ROM, but it would be nice if b-em supported both ROMs. We could either make this a new second processor type (which you could then use with a BBC B or whatever; I believe there were add-ons to allow this with real hardware) or make selecting it part of the Master Turbo option.

**Comment by hoglet67** [comment]
The other difference is it runs at 4MHz, compared to 3MHz for the external 65C02 Co Processor.

This difference is noticeable in Tube Elite,

**Comment by SteveFosdick** [comment]
I have implemented separate internal/external variant of the 6502 co-pro which load the correct boot ROM on the new Allegro 5 branch: https://github.com/stardot/b-em/tree/sf/allegro5

I have not got the speed correct as the existing way the speed is set relies on a shift value so is only changeable in powers of two, at least that's how it appears to me.

**Comment by SteveFosdick** [comment]
The last commit looks like a success:
![etube](https://user-images.githubusercontent.com/1048671/37991227-90a9e280-3200-11e8-879d-c5e3a54c8fcc.png)
![itube](https://user-images.githubusercontent.com/1048671/37991228-90c2192c-3200-11e8-85ac-406387f951b7.png)

**Comment by hoglet67** [comment]
Steve, you're doing some excellent work here.

**Comment by ZornsLemma** [comment]
Hear, hear! Thanks very much for this.

**Comment by kieranhj** [comment]
This is great.  I am planning to do some copro work for my real Master Turbo in the coming months and having it emulated properly will be invaluable.  I can test CLOCKSP on real hardware if that is useful?

**Comment by SteveFosdick** [comment]
This commit has been on the master branch for some time now.
