### ISSUE TITLE
Consider using default config when running from build dir

### ISSUE THREAD

**Issue by pau1ie** [stardot/b-em#59]
Previous versions of b-em would run from the build directory. This one won't because it can't find the config. Can you consider either:

- Adding the b-em executable directory to the search path
- Creating the config in the home directory if it doesn't exist

**Comment by SteveFosdick** [comment]
This should only be an issue starting for the first time as, wherever the config was found, it is saved back to the home directory ($XDG_CONFIIG_DIR) but you're right, it should be possible to run from within the build directory.  I'll add that to the search path.

**Comment by SteveFosdick** [comment]
I thought I had fixied this previously, but found I hadn't.  I think https://github.com/stardot/b-em/commit/c74a04b8f21208aa9ddabcf6eaf4215c6636479f finally nails it.

**Comment by pau1ie** [comment]
Thanks - the program now runs if the config doesn't exist.
However, If I try
`rm -rf ~/.config/b-em`

Then run b-em, I get an error message on exit saying:

`config: no suitable destination for config file - config will not be saved`

Can the b-em directory be created if it doesn't exist to avoid this? Alternatively the message might be changed to say where it wants to save the config.

**Comment by SteveFosdick** [comment]
It used to do that but I have just spotted a misplaced bracket in one of the later commits that will have nobbled that.  I'll fix that.

**Comment by SteveFosdick** [comment]
https://github.com/stardot/b-em/commit/d0977991cfded35fe15c28627e650d1e6d44b436 restores creating the config directory ($XDG_CONFIG_HOME or $HOME/.config/b-em) if it doesn't already exist.

**Comment by pau1ie** [comment]
Fixed! Thank you! And thank you for you excellent work on upgrading b-em, it is so much better now.
