### ISSUE TITLE
Build errors for tag allegro5-pre2 on Ubuntu 16.04

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#61]
I haven't spent a lot of time trying to investigate this myself, so don't take it too seriously, but FWIW I had a quick go at building this and it failed...

```
steven@riemann:~/src/b-em3/b-em$ make 2>&1 | head -20
Making all in src
make[1]: Entering directory '/home/steven/src/b-em3/b-em/src'
  CC       b_em-gui-allegro.o
gui-allegro.c:41:8: error: unknown type name ‘ALLEGRO_MENU’
 static ALLEGRO_MENU *disc_menu;
        ^
gui-allegro.c:58:31: error: unknown type name ‘ALLEGRO_MENU’
 static void add_checkbox_item(ALLEGRO_MENU *parent, char const *title, uint16_t id, bool checked)
                               ^
gui-allegro.c:66:28: error: unknown type name ‘ALLEGRO_MENU’
 static void add_radio_item(ALLEGRO_MENU *parent, char const *title, uint16_t id, int this_value, int cur_value)
                            ^
gui-allegro.c:71:27: error: unknown type name ‘ALLEGRO_MENU’
 static void add_radio_set(ALLEGRO_MENU *parent, char const **labels, uint16_t id, int cur_value)
                           ^
gui-allegro.c:87:28: error: unknown type name ‘ALLEGRO_MENU’
 static void add_sorted_set(ALLEGRO_MENU *parent, menu_map_t *map, size_t items, uint16_t id, int cur_value)
                            ^
gui-allegro.c:98:8: error: unknown type name ‘ALLEGRO_MENU’
 static ALLEGRO_MENU *create_file_menu(void)
steven@riemann:~/src/b-em3/b-em$ dpkg -l | grep -i allegro
ii  liballegro-acodec5-dev:amd64                  2:5.0.11-2                                   amd64        header files for the Allegro 5 audio codec addon
ii  liballegro-acodec5.0:amd64                    2:5.0.11-2                                   amd64        audio codec addon for the Allegro 5 library
ii  liballegro-audio5-dev:amd64                   2:5.0.11-2                                   amd64        header files for the Allegro 5 audio addon
ii  liballegro-audio5.0:amd64                     2:5.0.11-2                                   amd64        audio addon for the Allegro 5 library
ii  liballegro-dialog5-dev:amd64                  2:5.0.11-2                                   amd64        header files for the Allegro 5 dialog addon
ii  liballegro-dialog5.0:amd64                    2:5.0.11-2                                   amd64        dialog addon for the Allegro 5 library
ii  liballegro-image5-dev:amd64                   2:5.0.11-2                                   amd64        header files for the Allegro 5 image addon
ii  liballegro-image5.0:amd64                     2:5.0.11-2                                   amd64        image addon for the Allegro 5 library
ii  liballegro-physfs5-dev:amd64                  2:5.0.11-2                                   amd64        header files for the Allegro 5 physfs addon
ii  liballegro-physfs5.0:amd64                    2:5.0.11-2                                   amd64        physfs addon for the Allegro 5 library
ii  liballegro-ttf5-dev:amd64                     2:5.0.11-2                                   amd64        header files for the Allegro 5 TTF addon
ii  liballegro-ttf5.0:amd64                       2:5.0.11-2                                   amd64        TTF addon for the Allegro 5 library
ii  liballegro5-dev:amd64                         2:5.0.11-2                                   amd64        development files for the Allegro 5 library
ii  liballegro5.0:amd64                           2:5.0.11-2                                   amd64        portable library for cross-platform game and multimedia development
```

Let me know if you need any more information, of course.

Cheers.

Steve

**Comment by SteveFosdick** [comment]
That looks like it can't find the Allegro Native Dialogs addon which, according to the documentation, was introduced in Allegro 5.1 though I was developing against 5.2.

**Comment by SteveFosdick** [comment]
Just checked Ubuntu's package search and it seems 17.10 (artful) has Allegro 5.2 but for some reason Allegro went AWOL on 17.04.  I don't know how many other people would want to run B-Em on Ubuntu 16.04 so it's hard to say if it is worth trying to compile 5.2 against the libraries on 16.04 and make these available.

I wasn't being awkward in choosing a relatively new version of Allegro 5 - it was the native dialogs add-on that made it a reasonable prospect as part of the idea was to stop having separate UIs for each OS and, having dropped the previous UI that was internal to Allegro4 and having not yet implemented the native dialogs add-on, Allegro 5.0 doesn't really have a solution as to how to have a cross-platform UI.

**Comment by hoglet67** [comment]
There are pre-compiled packages for Allegro 5.2.4 available for Ubuntu 16.04 here:
https://launchpad.net/~allegro/+archive/ubuntu/5.2

I was able to build against these yesterday with no problems at all.

The only issue is that allegro5-dev and allegro4-dev are marked as incompatible, so if you install one the other is removed. It only takes about 30s to switch though, so not a huge issue. This only affects the -dev packages, not the runtime libraries.

**Comment by ZornsLemma** [comment]
Thanks for taking a look at this. I am currently using 16.04 because it's a Long Term Support release, but the next LTS is due out any moment now so I will be upgrading within a month or two. I don't think it's worth going to any trouble to support 16.04, although judging from hoglet's comment it's not a big deal to build on 16.04 if you know where to get the Allegro 5.2.4 packages. I'd suggest including a version of that comment in the release notes though.

**Comment by ZornsLemma** [comment]
Incidentally, if this new version of Allegro allows a better UI I'm all for it. I look forward to seeing it!

**Comment by elminster** [comment]
You can also run one of my docker images, as long as you dont want sound, they will run om anything that docker will run on. Possibly more hassle (certainly more space usage) than getting Allegro packages, but easier than doing a OS upgrade or running a VM. I do need to document how to use them, on my todo list.

**Comment by SteveFosdick** [comment]
Thanks, elminster.

Referring back to my previous post when I said Allegro went AWOL on 17.04 it seems 17.,04 itself has disappeared.  I did run Ubuntu years ago but I am a bit out of touch with their release process.

**Comment by elminster** [comment]
They generally retire all version in a major version except one they keep as an LTS. 17.10 is the LTS version of 17.xx. My containers use 17.10 but I have a 17.04 VM kicking around and Allegro5 version worked on that without issue. Was only 16.xx that had problems using the standard packages.

**Comment by SteveFosdick** [comment]
As the new LTS release was due "any moment now" a year ago I will close this on the basis it has been solved by a new release of Ubuntu,  If that is not the case feel free to re-open.
