### ISSUE TITLE
In preview release, Eject Disc menu option is non-functional along with new-disc option.

### ISSUE THREAD

**Issue by afarlie** [stardot/b-em#69]
In B.EM 2.2  The Eject disc menu option allows for a disc to be ejected.

In the current preview release this option appears to have NO effect, the loaded disc remaining on the menu.

In B-EM 2.2 , New disc menu option is supposed to create a new disc image.

This option appears to be non-functional in the current preview release, as it asks for a filename and then says it can't find it.

**Comment by SteveFosdick** [comment]
Eject is fixed in dcb675e3224da5b5d7ea705cbaec61f219471112
and New Disc in  5318931babcc6b9910e4762c6932266e2f29a884 both now in master.

**Comment by afarlie** [comment]
Thanks.. Is there a way to get  a preview build?

**Comment by SteveFosdick** [comment]
There are windows build instructions on the Wiki: https://github.com/stardot/b-em/wiki

If not I will see if I can get around to this tomorrow or Tuesday.

**Comment by SteveFosdick** [comment]
See https://github.com/stardot/b-em/releases/tag/allegro5-pre3

**Comment by SteveFosdick** [comment]
As I have heard nothing since, I assume this is OK.  Please re-open if not.
