### ISSUE TITLE
Music 5000/4000 problem in b-em. Cannot "MAKE"

### ISSUE THREAD

**Issue by ghost** [stardot/b-em#73]
I have tried all the versions. TheI recorder and staff editor appear to work well with a midi keyboard as you can enter and PLAY data in both editors. When I try to NAME or MAKE the data into a WORD it disappears. Is there a fix or workaround for this. I would like to create some new ample music files.

**Comment by SteveFosdick** [comment]
As discussed on the forums, it seems this was an unintended consequence to a patch that been applied to the AMPLE ROM upstream of B-Em.  B-Em now includes an AMPLE ROM patched in a different way and a virgin AMPLE ROM which I believe fixes the issue.

**Comment by ghost** [comment]
All working well for me now. Thanks
