### ISSUE TITLE
Unable to create display

### ISSUE THREAD

**Issue by pau1ie** [stardot/b-em#74]
Having updated Arch linux, I am getting "Unable to create display". No more information is given as to why. This was with v-2f7024c which previously worked. I also tried updating to v-f1dd7d2.

I am happy to help debug this issue.

**Comment by pau1ie** [comment]
Looking at stardot here: https://stardot.org.uk/forums/viewtopic.php?f=4&t=11983&p=217350&hilit=music+5000+system+disc#p217398 I note it tries allegro-gtk. I removed gnome from my system, as it was getting too slow on my aging laptop. I'm not sure if gtk is still there or not though. ldd shows that /usr/lib/libgtk-x11-2.0.so.0.2400.32 is linked in, so presumably I do still have gtk installed.

**Comment by SteveFosdick** [comment]
Library dependencies is certainly one possibility.  Another is that GNOME has customised GTK in your personal config files in a way that is not compatible with standaline GTK.  To test this, try creating a new user who has never logged into GNOME and see if B-Em will work under that user.  If so, you may need to do some config clean-up.  If not then I think we're back to libraries and possibly missing dependencies.

**Comment by pau1ie** [comment]
[strace.zip](https://github.com/stardot/b-em/files/2536284/strace.zip)
Created a new user and I get the same error. I upload a zip file containing the ldd output (I installed it in /usr/local/bin). I also include the output of strace when running it as the new user (test1).

**Comment by SteveFosdick** [comment]
Comparing the ldd output with mine (where it works) the number in brackets () is different for every line but the short name and where it has been found in the filesystem is the same between your system and mine - I am running Arch too.  I'll move on to the strace.

**Comment by SteveFosdick** [comment]
Your strace file has a whole bunch of stuff related to libcanberra-gtk from lines 1094 to 1171 that is not my in my strace.  Then at line 1416 in your strace it fails to find the Adwaita theme whereas in my trace it opens and loads it.

Later, at line 1690 it looks like it is request GLX graphics and shortly after that is the error message.  By that stage mine is doing various stuff with the I915 driver.  One possibility is that GNOME, by virtue of having a composited desktop and fancy transitions etc. uses 3D graphics and pulls in the librarries for that and LXDE does not, so they have been uninstalled.  if so the 3D libraries must be loaded dynamically on demand.

**Comment by SteveFosdick** [comment]
Ok, as an experiment I created a virtual machine in VirtualBox and installed Arch Linux on it.  Apart from the base package set from pacstrap I also installed: syslinux, lxde, unzip, openssh, allegro but nothing else.  When I went to install LXDE it asked me about GL and offered an NVIDIA option and another one so, as I don't believe VirtualBox emulates an Nvidia card and pass through to the host wouldn't expose an NVDIA card either, I choose the non-NVIDIA option.

B-Em works fine on this.

**Comment by pau1ie** [comment]
I have a Radeon display, and it is pretty old. I understand radeon tends to be less well supported than nvidia, so maybe the it is something to do with that.

$ lspci | grep -i vga
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Madison [Mobility Radeon HD 5650/5750 / 6530M/6550M]

I hope to buy a new laptop in the next few months, so hopefully that will just work!

**Comment by SteveFosdick** [comment]
I still think it would be worth checking if the GLX drivers for the card you actually have are installed. See https://wiki.archlinux.org/index.php/ATI

**Comment by pau1ie** [comment]
Thank you for your help. I think it was because I had held back mesa because of this issue. 
https://bbs.archlinux.org/viewtopic.php?pid=1815389#p1815389
I removed the hold, and upgraded, and everything works. Apologies - this was nothing to do with b-em (Which you knew already of course). Thanks again.
