### ISSUE TITLE
Application crash on switch to full-screen.

### ISSUE THREAD

**Issue by afarlie** [stardot/b-em#76]
Open B-EM standardly, selected Fullscreen from Video menu - application crashed with the following:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	b-em.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5b8f12da
  Fault Module Name:	allegro-5.2.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	584e234a
  Exception Code:	c0000005
  Exception Offset:	00024997
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

This is on Windows 7 32bit...   and the Allegro 5 preview 3 release. 

Would like to someone to confirm this crash though...

**Comment by afarlie** [comment]
Also on the October 2018 (Music 3000) release - 
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	b-em.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5bbe5bf6
  Fault Module Name:	allegro-5.2.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	584e234a
  Exception Code:	c0000005
  Exception Offset:	00024997
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by SteveFosdick** [comment]
Sorry this has been sitting unanalysed for so long, but given the length of time , could you re-rest the current master or a recent Windows pre-build pre-release from: https://github.com/stardot/b-em/releases

**Comment by SteveFosdick** [comment]
I cannot reproduce this on the current master on either Linux or Windows (VirtualBox).  Please re-open if it is still an issue.
