### ISSUE TITLE
Provide a menu option to set a "nice" window size

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#79]
If I resize the b-em window, the scaling of the display gives me ragged pixels. If I do this on BeebEm I can choose something from the Window menu to set the window back to a neat 640x512; on b-em I can't see anything like this and I have to manually resize the window until it looks right, but unless I get it exactly right by chance I'm going to get a bit of unevenness caused by the scaling. I'd really like to just be able to set it to the precisely "right" size.

Alternatively/instead, an option to disallow manual resizing of the b-em window might be nice; I can see uses for it but personally I'd rather not be able to accidentally resize the window and introduce the scaling artefacts.

**Comment by SteveFosdick** [comment]
That's a good suggestion and not too hard to do.  In the meantime there is a workaround.  From the Settings->Video menu choose a different border size and then choose your preferred size again.  Changing border size re-sizes the window so the bit of the display actually drawn on is 1:1 and the border is extra.

**Comment by ZornsLemma** [comment]
Thanks, that works - but it looks like I might have found a small bug by chance while trying it out. If I start up (just for reproducibility) in Master 128 mode (OS 3.20) and do *HELP twice to fill the screen with text, then drag the window to enlarge it and then choose Settings->Video->Borders->Medium, I get some corruption in the bottom border:
![Screenshot at 2019-05-06 20-21-47](https://user-images.githubusercontent.com/7988240/57249371-aaf45a00-703c-11e9-800d-f1b79114c9fe.png)
I didn't strictly follow your instructions, I was already on borders "Medium", but I guess it's not right there is corruption all the same. Should I raise a separate issue for this?

**Comment by SteveFosdick** [comment]
Implemented in commit f03dba81612a1152699024d3f60ad1b1a60ce70a on branch sf/issue#86

**Comment by SteveFosdick** [comment]
I forgot to say, as far as I can tell the screen corruption is also fixed by a previous commit on the same branch.
