### ISSUE TITLE
Typo in SRAM help in VDFS

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#81]
If you do *HELP SRAM it says "*Sideays* RAM commands".

I wonder if it should also output a newline before that line? I'm not sure, but in Master mode if I do *HELP SRAM there's no gap between the output from the DFS's SRAM output and that for VDFS. And if I *UNPLUG so only DFS or only VDFS is installed, the built-in DFS's *HELP SRAM starts with a newline and VDFS's doesn't.

I'm happy to create a pull request for either of these issues if it would help, but it may be as easy for you to just fix them on master; let me know.

**Comment by SteveFosdick** [comment]
Ok, the spelling one is easy to fix.  Newlines in *HELP seems to have been a hot topic in the past with people disagreeing as to what is "standard".  What looks good seems to depend on what ROMs you have installed in what order.  I'll check it out, maybe later today or at the weekend.

**Comment by SteveFosdick** [comment]
These changes are merged into master.

**Comment by ZornsLemma** [comment]
Cheers, FWIW that looks good to me.

**Comment by SteveFosdick** [comment]
The fix is now merged to master.
