### ISSUE TITLE
Disc image file picker - allow uppercase extensions

### ISSUE THREAD

**Issue by pau1ie** [stardot/b-em#85]
Writing an image to ssd with the datacentre created an uppercase filename for the image. The file picker only allows lower case extensions. A simple fix is to add the uppercase extensions to the list if allowed values, though I haven't given any thought as to whether this would cause other problems. Here is a patch to do what I suggest for you to consider.

[upperfiles.txt](https://github.com/stardot/b-em/files/3209495/upperfiles.txt)

**Comment by SteveFosdick** [comment]
Patch applied to master.  Do I take it this is on Linux?

**Comment by pau1ie** [comment]
Yes, I was testing on Linux. Thanks, works nicely for me!
