### ISSUE TITLE
hdfmt.c doesn't work

### ISSUE THREAD

**Issue by pau1ie** [stardot/b-em#90]
It seems on Linux I would use the following to create a disc image:
```
mkdir ~/.config/b-em/scsi
hdfmt ~/.config/b-em/scsi/scsi0 1g
```

However, when I do this it creates a file much smaller than I expected. I had a look at the code. I feel I ought to be able to debug this, but I can't. I did notice though that the fwrite command at line 91 only writes the initial sectors, there doesn't seem to be a mechanism for writing the rest of the empty sectors.

When I try to use the disc image in b-em, I get `Disc error 50 at :4/000002`. I expect this is because it is trying to read the missing sectors.

I note it only gets compiled (by the makefile) in Windows but even there doesn't seem to be included in the distribution.

At the error message in line 153, the size is in `argv[2]`, rather than `argv[1]`.

**Comment by SteveFosdick** [comment]
Writing the initial sectors was deliberate.  The ADFS should not be trying to write sectors it has not previously written so for an empty disc with no files on it the only things the ADFS needs to read are the free space map and the root directory and these are included in the initial sectors the hdfmt program write.

To test this I tried creating a new hard disc with:

`hdfmt ~/.config/b-em/scsi/scsi0 100m`

and then started B-Em with ADFS as the default filing system.  This gave me a BASIC prompt and upon issuing the `*.` command it gave me an empty directory.

It does give an error in Master 512 mode, i.e. with the 80186 co-processor.  DosPlus on this co-processor has its own filing system inside an ADFS file but I am not convinced whether this actually uses ADFS to access this or whether it uses direct sector access.

Once having booted from the floppy and run the hdisk program to initialise this image file it will then happily boot from the hard disc.

I'll fix the error message and then see what the 80186 is doing.

**Comment by SteveFosdick** [comment]
On looking into this a bit further, the error message `Disc error 50 at :4/000002` is actually referring to the first floppy and not the SCSI hard disc at all.  With a HD present ADFS uses disc numbers 0-3 for hard discs so this first floppy becomes drive 4 rather than drive 0.  The message also appears after the floppy disc noise (if you have than enabled).

So what is happening is that the 80186 boot code has found nothing bootable on the hard disc and is then trying to boot the floppy.  This is either empty of has a disc in the wrong format loaded.

**Comment by SteveFosdick** [comment]
BTW, if you're trying to install DOSPlus/GEM it is worth picking up the latest master or the sf/issue90 branch as I have also fixed a big where the 2nd and subsequent Master 512 discs were accessed with the wrong side setting, i.e. sequential rather than interleaved.
